### ISSUE TITLE
OAuth API error when trying to login for external apps

### ISSUE THREAD

**Issue by MacTwister** [fablabbcn/fablabs.io#587] opened 2021-09-02 09:33 UTC
**Describe the bug**
It has been reported that in the last 2 days, users have been unable to login through fablabsio (ie. Nueval, Fabcloud). 

When the app redirects to the authentication URL, `https://api.fablabs.io/oauth/authorize?response_type=code&redirect_uri=....etc...`, the following error is thrown:
```
translation missing: en.doorkeeper.errors.messages.invalid_request.missing_param
```

Has anything been updated in the Doorkeepr library version or config?

**To Reproduce**
1. Go to Nueval (make sure you are logged out)
2. Click on login with fablabsio

**Comment by pral2a** [comment] 2021-09-02 09:55
We'll look at it asap! I can confirm other apps log in such as https://make.works/ work well

**Comment by viktorsmari** [comment] 2021-09-02 11:31
I can also log in to https://make.works/  using fablabs.io without issues.

The doorkeeper plugin was updated: 2021-04-20 and we have not deployed since then, so this is the issu:
https://github.com/fablabbcn/fablabs.io/blame/78d33975c9b9a36bad211999e9bbccc6cfc1646d/Gemfile.lock#L153

This commit a1782ea9027959832aca61f46bd1a56948c8162b updates

Doorkeeper 5.0.3 -> 5.5.1

**Comment by viktorsmari** [comment] 2021-09-02 12:05
Fixed by downgrading Doorkeeper - but we should keep this issue as a reminder that we need some kind of test to prevent breaking Nueval login in the future.

**Comment by MacTwister** [comment] 2021-09-02 12:19
Please in future if you make a change to the Fablabsio login system, which is used by other applications, it would be good to notify the network of pending changes (or at least me for Nueval/Fabcloud). This way we can test the updates and synchronise any needed changes in our apps in a timely fashion, instead of now chasing a fix after 2 days of having a broken login on other apps.

**Comment by MacTwister** [comment] 2021-09-10 14:04
Ok thanks @pral2a  & @viktorsmari  for quick revert. Had a bit of time today to review this and indeed Doorkeepr will now require a scope to be defined for auths. Since this app does not use scopes, we can also define a default scope for requests that do not define one. 

From upgrade guide: https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions#from-51x-to-52x

**Closed** 2022-01-27 09:06 UTC
